Fix acceptance test build (#1247)
* Install docker compose the recommended way

We were using installation via `pip` and the build started to fail with the following error all of a sudden:
```
2020-11-25T14:44:52.350Z /usr/local/lib/python3.5/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
2020-11-25T14:44:54.357Z   from cryptography.hazmat.backends import default_backend
2020-11-25T14:44:54.357Z Traceback (most recent call last):
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/jsonschema/__init__.py", line 31, in <module>
2020-11-25T14:44:54.357Z     from importlib import metadata
2020-11-25T14:44:54.357Z ImportError: cannot import name 'metadata'
2020-11-25T14:44:54.357Z 
2020-11-25T14:44:54.357Z During handling of the above exception, another exception occurred:
2020-11-25T14:44:54.357Z 
2020-11-25T14:44:54.357Z Traceback (most recent call last):
2020-11-25T14:44:54.357Z   File "/usr/local/bin/docker-compose", line 7, in <module>
2020-11-25T14:44:54.357Z     from compose.cli.main import main
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/compose/cli/main.py", line 24, in <module>
2020-11-25T14:44:54.357Z     from ..config import ConfigurationError
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/compose/config/__init__.py", line 6, in <module>
2020-11-25T14:44:54.357Z     from .config import ConfigurationError
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/compose/config/config.py", line 51, in <module>
2020-11-25T14:44:54.357Z     from .validation import match_named_volumes
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/compose/config/validation.py", line 12, in <module>
2020-11-25T14:44:54.357Z     from jsonschema import Draft4Validator
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/jsonschema/__init__.py", line 33, in <module>
2020-11-25T14:44:54.357Z     import importlib_metadata as metadata
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 43, in <module>
2020-11-25T14:44:54.357Z     class PackageNotFoundError(ModuleNotFoundError):
2020-11-25T14:44:54.357Z NameError: name 'ModuleNotFoundError' is not defined
```

Install as recommended here: https://github.com/docker/compose#linux

Verify checksum of the downloaded release: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64.sha256