Fix 500 when creating/updating event type with invalid regex in the schema
Prior to this fix, when creating a new event type with the following
schema:

```
    {
      "properties": {
        "foo": {
          "type": "string",
          "pattern": "^(?!\\\\s*$).+"
        }
      }
    }
```

Would result in 500 and no further explanation to the user. The user
would have to get in contact with the FlowId and we would have to dive
in the logs to find out a stack trace similar to this:

```
com.google.re2j.PatternSyntaxException: error parsing regexp: invalid or unsupported Perl syntax: `(?!`

        at com.google.re2j.Parser.parsePerlFlags(Parser.java:1139)
        at com.google.re2j.Parser.parseInternal(Parser.java:825)
        at com.google.re2j.Parser.parse(Parser.java:802)
        at com.google.re2j.RE2.compileImpl(RE2.java:183)
        at com.google.re2j.Pattern.compile(Pattern.java:136)
        at com.google.re2j.Pattern.compile(Pattern.java:96)
        at org.everit.json.schema.StringSchema.<init>(StringSchema.java:103)
        at org.everit.json.schema.StringSchema$Builder.build(StringSchema.java:34)
        at org.everit.json.schema.StringSchema$Builder.build(StringSchema.java:20)
        at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:68)
        at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:62)
        at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:85)
        at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:80)
        at java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
        at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:80)
        at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:59)
        at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:31)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:31)
        at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:446)
        at org.everit.json.schema.loader.SchemaLoader.sniffSchemaByProps(SchemaLoader.java:471)
        at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:336)
        at org.everit.json.schema.loader.SchemaLoader.lambda$loadSchemaObject$4(SchemaLoader.java:380)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:378)
        at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:421)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:253)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:236)
        at org.zalando.nakadi.service.EventTypeService.validateSchema(EventTypeService.java:596)
        at org.zalando.nakadi.service.EventTypeService.create(EventTypeService.java:177)
        at
        org.zalando.nakadi.service.EventTypeServiceTest.throwsInvalidSchemaOnInvalidRegex(EventTypeServiceTest.java:320)
```

This regex library is not the default one and it was our choice to use
it in the past, given there were some security vulnerabilities with
the default regex library.

One could argue that it's weird to capture an exception from a third
library when checking for the validity of the schema and that the
everit library should probably wrap it in the already handled
`SchemaException` but since we configured this third library I would
say that it's fine as is.

Now the user will get a 422 with a nicer message: `invalid regex pattern in the schema: invalid or unsupported Perl syntax "(?!"`